---
nodepool_changes:
 - 'openstack/tripleo-quickstart-extras:master:refs/changes/28/509728/30'
 - 'openstack/tripleo-quickstart:master:refs/changes/01/579601/7'
 - 'openstack/tripleo-heat-templates:master:refs/changes/03/579603/3'

nodepool_delorean_hash: 46f750edae74225a4dfbcce1f70990e1122a9613_815ab44a
nodepool_delorean_hash_newest: 927c7c215ce130bca240f5ed077bd6d2771cf6e4_5feddecb
